return {
    ACTIONS = {
        SMELT = "Smelt",
    },
    NAMES = {
        ALLOY = "Alloy",
        APORKALYPSE_CLOCK = "Aporkalypse Calendar",
        ARMOR_METALPLATE = "Tin Suit",
        ARMOR_WEEVOLE = "Weevole Mantle",
        ASPARAGUS_PLANTED = "Asparagus",
        BASEFAN = "Oscillating Fan",
        CHITIN = "Chitin",
        CUTNETTLE = "Nettle",
        DUNGBALL = "Dung Ball",
        DUNGBEETLE = "Dung Beetle",
        DUNGPILE = "Dung Pile",
        FLOWER_RAINFOREST = "Exotic Flower",
        GLOWFLY = "Glowfly",
        GLOWFLY_COCOON = "Glowfly Cocoon",
        GNAT = "Gnat Swarm",
        GNATMOUND = "Gnat Mound",
        GRASS_TALL = "Tall Grass",
        HALBERD = "Halberd",
        IRON = "Iron Ore",
        PEAGAWK = "Peagawk",
        PEAGAWKFEATHER = "Peagawk Plume",
        PEAGAWK_BUSH = "Blinkbush",
        POG = "Pog",
        RABID_BEETLE = "Rabid Beetle",
        SEDIMENTPUDDLE = "Sparkling Pool",
        SHEARS = "Shears",
        SMELTER = "Smelter",
        TREE_PILLAR = "Great Leafy Stalk",
        WEEVOLE = "Weevole",
        WEEVOLE_CARAPACE = "Weevole Carapace",
    },
    RECIPE_DESC = {
        ARMOR_METALPLATE = "Strong and sturdy.",
        ARMOR_WEEVOLE = "Kinda gross, but surprisingly strong.",
        BASEFAN = "Relieves hay fever, keeps you dry.",
        HALBERD = "Pointy and hurty.",
        SHEARS = "Cut your way into adventure.",
        SMELTER = "Turn Iron into Alloy.",
    },
    UI = {
        CUSTOMIZATIONSCREEN = {
            ASPARAGUS = "Asparagus",
            ASPARAGUS_REGROWTH = "Asparagus",
            DEEP_JUNGLE_FERN_NOISE = "Jungle Floor Ferns",
            DUNGBEETLE = "Dung Beetle",
            DUNGBEETLE_SETTING = "Dung Beetle",
            DUNGPILE = "Dung Pile",
            FOG = "Fog",
            GLOWFLYCYCLE = "Glowfly Cycle",
            GLOWFLY_SETTING = "Glowfly",
            GNATMOUND = "Gnat Mound",
            GNAT_SETTING = "Gnat Swarm",
            GRASS_TALL = "Tall Grass",
            GRASS_TALL_PATCH = "Infected Tall Grass",
            HAYFEVER = "Hayfever",
            HUMID = "Humid",
            JUNGLE_BORDER_VINE = "Jungle Canopy Vines",
            LUSH = "Lush",
            PEAGAWK_SETTING = "Peagawk",
            PEAGAWK_SPAWNER = "Peagawk",
            PL_CLOCKTYPE = "Clock Type",
            POG = "Pog",
            PORKLAND_SEASON_START = "Porkland Starting Season",
            TEMPERATE = "Temperate",
            WEEVOLE_SETTING = "Weevole",
        },
        SANDBOXMENU = {
            CHOOSEWORLD = "Choose World",
            CLOCKTYPE_DEFAULT = "Default",
            CLOCKTYPE_PORKLAND = "Plateau",
            HUMID = "Humid",
            LOCATIONTABNAME = {
                PORKLAND = "Porkland",
            },
            LUSH = "Lush",
            PORKLAND_DEFAULT = "Temperate",
            TEMPERATE = "Temperate",
        },
        SERVERLISTINGSCREEN = {
            SEASONS = {
                APORKALYPSE = "Aporkalypse",
                HUMID = "Humid",
                LUSH = "Lush",
                TEMPERATE = "Temperate",
            },
        },
    },
}
