return {
    ANNOUNCE_DEHUMID = {
        "Ah, so much better.",
    },
    ANNOUNCE_GNATS_DIED = "Take that, bugs!",
    ANNOUNCE_HAYFEVER = "My nose feels.. itchy.",
    ANNOUNCE_HAYFEVER_OFF = "I don't want to claw my eyes out anymore.",
    ANNOUNCE_PICKPOOP = {
        "Eugg!",
        "Gross!",
        "Ick!",
        "I got some on my hands!",
    },
    ANNOUNCE_SNEEZE = "AHHH CHOOOO!",
    ANNOUNCE_TOO_HUMID = {
        "This %s is so heavy.",
        "This %s is too hot.",
    },
    DESCRIBE = {
        ALLOY = "Ahoy there, alloy!",
        APORKALYPSE_CLOCK = "Looks scientifically apocalyptic.",
        ARMOR_METALPLATE = "Science says I'm safe in here.",
        ARMOR_WEEVOLE = "Yeesh. This is kinda creepy.",
        ASPARAGUS_PLANTED = "I should pick those!",
        BASEFAN = "Fan-tastic.",
        CHITIN = "Bug coating.",
        CUTNETTLE = "Science says the sharp edges are good for my lungs.",
        DUNGBALL = "Most definitely poop.",
        DUNGBEETLE = {
            DEAD = "Dung for.",
            GENERIC = "She's on a roll.",
            SLEEPING = "She's pooped.",
            UNDUNGED = "She needs to get her dung together.",
        },
        DUNGPILE = {
            GENERIC = "It's a pile of dung.",
            PICKED = "Dung and dung.",
        },
        FLOWER_RAINFOREST = "It smells vaguely tolerable.",
        GLOWFLY = {
            DEAD = "Lights out forever.",
            GENERIC = "A light aflight.",
            SLEEPING = "Out like a light.",
        },
        GLOWFLY_COCOON = "Snug as a bug.",
        GNAT = "Better gnat go near those guys.",
        GNATMOUND = "Science says it's gnat good.",
        GRASS_TALL = {
            BURNING = "A grass fire!",
            GENERIC = "It's too tough to pick with my hands.",
            PICKED = "Looks like I got it all.",
        },
        HALBERD = "Now I can't be caught off-guard.",
        IRON = "Isn't it ironic?",
        PEAGAWK = {
            DEAD = "Dead-eyed.",
            GENERIC = "That bush is alive!",
            SLEEPING = "It's getting some shut-eye.",
        },
        PEAGAWKFEATHER = "Still blinking.",
        PEAGAWK_BUSH = "Look! An iris bush.",
        POG = {
            APORKALYPSE = "Yikes! What's that!",
            FOLLOWER = "It's friendly, for now.",
            GENERIC = "Science says it's always hungry.",
            SLEEPING = "I'll let it rest.",
        },
        RABID_BEETLE = {
            DEAD = "A late beetle.",
            GENERIC = "Looks deranged.",
            SLEEPING = "In a slumber.",
        },
        SEDIMENTPUDDLE = "Pool's gold.",
        SHEARS = "Shear-ly delightful.",
        SMELTER = {
            BURNT = "The smelter got smelted.",
            COOKING_SHORT = "This is going to take a while.",
            DONE = "It's done!",
            EMPTY = "I smelt that!",
        },
        TREE_PILLAR = "It totally blocks out the sun.",
        WEEVOLE = "Whee!",
        WEEVOLE_CARAPACE = "I'll be careful with this carapace.",
    },
}
