return {
    ANNOUNCE_DEHUMID = {
        "Ah, I feel better now.",
    },
    ANNOUNCE_GNATS_DIED = "Thank God.",
    ANNOUNCE_HAYFEVER = "Ugh! My allergies!",
    ANNOUNCE_HAYFEVER_OFF = "I think... my nose has cleared!",
    ANNOUNCE_SNEEZE = "Atchoum!",
    ANNOUNCE_TOO_HUMID = {
        "Mon dieu! This %s is humid.",
        "Whew. This %s is hot.",
    },
    DESCRIBE = {
        ALLOY = "Metal cooked to perfection.",
        APORKALYPSE_CLOCK = "Like the knobs on a stove, it must be turned just right.",
        ARMOR_METALPLATE = "Like an armor made of tin cans.",
        ARMOR_WEEVOLE = "It still smells of bug.",
        ASPARAGUS_PLANTED = "I should snatch those up.",
        BASEFAN = "Good ventilation in the kitchen is an must.",
        CHITIN = "Completely inedible.",
        CUTNETTLE = "Great for clearing the sinuses!",
        FLOWER_RAINFOREST = "Edible?",
        GLOWFLY = {
            DEAD = "Such a shame. And not even edible.",
            GENERIC = "Light the way, mon amie.",
            SLEEPING = "May your dreams be full of light.",
        },
        GLOWFLY_COCOON = "It's wrapped itself like a cabbage roll.",
        GNAT = "The bugs are really bad around here.",
        GNATMOUND = "I'd rather have a mound of chocolate.",
        GRASS_TALL = {
            BURNING = "Smells like a cookout!",
            GENERIC = "Too long to cut with my hands.",
            PICKED = "It will have to grow back.",
        },
        HALBERD = "I dislike fighting.",
        IRON = "I wonder what I could cook up with this.",
        PEAGAWK = {
            DEAD = "A pointless death.",
            GENERIC = "Those feathers would make a nice table centerpiece.",
            SLEEPING = "Those eyes are unnerving.",
        },
        PEAGAWKFEATHER = "It's quite soft.",
        PEAGAWK_BUSH = "It's a bright blue bush.",
        POG = {
            APORKALYPSE = "I suppose this happens when you feed the wildlife.",
            FOLLOWER = "Mon petit chou.",
            GENERIC = "Great for feeding my kitchen scraps!",
            SLEEPING = "Au revoir.",
        },
        RABID_BEETLE = {
            DEAD = "A shame. Not even edible.",
            GENERIC = "It is like me when I am hungry.",
            SLEEPING = "What a curious way to sleep!",
        },
        SHEARS = "Good for cutting hedges and grass.",
        SMELTER = {
            BURNT = "I'm better at cooking food than metal.",
            COOKING_SHORT = "The flavors are fusing.",
            DONE = "Fresh out of the oven! Be careful with the scalding.",
            EMPTY = "'Smelt' bad, if you ask me.",
        },
        TREE_PILLAR = "What a marvel.",
        WEEVOLE = "Shoo! Go away!",
        WEEVOLE_CARAPACE = "The crust of a bug.",
    },
}
