return {
    ANNOUNCE_DEHUMID = {
        "The heat has lifted but my heart has not.",
    },
    ANNOUNCE_GNATS_DIED = "It's not my turn yet.",
    ANNOUNCE_HAYFEVER = "Ugh. Even my sinuses are suffering.",
    ANNOUNCE_HAYFEVER_OFF = "My sinuses are clear, but suffering continues.",
    ANNOUNCE_PICKPOOP = {
        "Sigh.",
        "Ew.",
        "Everything is suffering.",
    },
    ANNOUNCE_SNEEZE = "achoo! achoo! sniff.",
    ANNOUNCE_TOO_HUMID = {
        "This %s is heavier in the heat.",
        "This %s is too hot. It weighs on my soul.",
    },
    DESCRIBE = {
        ALLOY = "Cold and hard, like my existence.",
        APORKALYPSE_CLOCK = "Clockwork for the end of times.",
        ARMOR_METALPLATE = "Like a metal coffin that keeps me alive.",
        ARMOR_WEEVOLE = "Something died so that this armor may exist.",
        ASPARAGUS_PLANTED = "I should rip those out of the ground.",
        BASEFAN = "Alas the relief it brings is only temporary.",
        CHITIN = "This shell is poor protection from life's horrors.",
        CUTNETTLE = "I suppose these will cure blocked sinuses.",
        DUNGBALL = "Grotesque.",
        DUNGBEETLE = {
            DEAD = "How I envy you.",
            GENERIC = "A symbol of the ugliness of this world.",
            SLEEPING = "Even the hideous sleep sounder than I.",
            UNDUNGED = "Alas, she has fallen from her grotesque perch.",
        },
        DUNGPILE = {
            GENERIC = "There's dreadfulness everywhere.",
            PICKED = "That was... unpleasant.",
        },
        FLOWER_RAINFOREST = "It, too, will wither and die one day.",
        GLOWFLY = {
            DEAD = "Its light hath been extinguished forever.",
            GENERIC = "A small light in a dark world.",
            SLEEPING = "Having dark dreams, no doubt.",
        },
        GLOWFLY_COCOON = "If I could climb into a cocoon I would never emerge.",
        GNAT = "Like life, they wear you down little by little.",
        GNATMOUND = "They're building their own doom.",
        GRASS_TALL = {
            BURNING = "Death comes to everything.",
            GENERIC = "Alas, I'm too weak to pick it.",
            PICKED = "All things end.",
        },
        HALBERD = "A terrible weapon for a terrible world.",
        IRON = "Iron. Like my heart.",
        PEAGAWK = {
            DEAD = "Beautiful death.",
            GENERIC = "Many eyes witness many horrors in life.",
            SLEEPING = "Alas, only a momentary reprieve from life.",
        },
        PEAGAWKFEATHER = "I spy, with my little eye...",
        PEAGAWK_BUSH = "Just a bush...",
        POG = {
            APORKALYPSE = "I see. Even you turn on me, in the end.",
            FOLLOWER = "I cannot protect you from death.",
            GENERIC = "Even you cannot escape death.",
            SLEEPING = "Are you practicing being dead?",
        },
        RABID_BEETLE = {
            DEAD = "Lifeless.",
            GENERIC = "As rabid as death itself.",
            SLEEPING = "Sleep is not a permanent escape from life.",
        },
        SEDIMENTPUDDLE = "Contains unreachable shiny things.",
        SHEARS = "Can it shear my heart?",
        SMELTER = {
            BURNT = "It blazes with more passion than I know.",
            COOKING_SHORT = "They struggle in the fire and brimstone.",
            DONE = "Born of fire.",
            EMPTY = "Burn who are trapped in it...",
        },
        TREE_PILLAR = "Ancient, and full of life.",
        WEEVOLE = "Its sole existence is to annoy me.",
        WEEVOLE_CARAPACE = "Bits of bug carcass.",
    },
}
